---
- hosts: web
  vars:
    mysql_root_password: fart
  tasks:
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    become: yes
    with_items:
    - python3-mysqldb
    - mysql-server
  - name: Start the MySQL service
    become: yes
    service: 
      name: mysql 
      state: started
      enabled: true
  - name: Create database user with name 'bob' and password '12345' with all database privileges
    community.mysql.mysql_user:
      login_user: root
      name: bob
      password: 12345
      priv: '*.*:ALL'
      state: present