name: Ansible Configuration EC2

on:
  workflow_run:
    workflows: ["Terraform Provision EC2"]
    types:
      - completed  # Triggered after Terraform workflow completes

jobs:
  ansible-provision:
    name: Provision EC2 with Ansible
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Download the EC2 public IP from the previous workflow's artifact
    - name: Download EC2 Public IP
      uses: actions/download-artifact@v4
      with:
        name: ec2_public_ip
        path: ./artifact

    # Set up Ansible
    - name: Set up Ansible
      run: sudo apt-get install -y ansible

    # Configure SSH key for Ansible (using GitHub Secrets)
    - name: Configure SSH key
      run: |
        echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    # Get the EC2 IP address from the downloaded artifact
    - name: Set EC2 IP
      id: set_ip
      run: |
        EC2_IP=$(cat ./artifact/ec2_public_ip.txt)
        echo "::set-output name=ec2_ip::$EC2_IP"

    # Wait for the EC2 instance to be ready
    - name: Wait for EC2 instance to be ready
      run: |
        while ! nc -z -w 5 ${{ steps.set_ip.outputs.ec2_ip }} 22; do
          echo "Waiting for EC2 instance to be ready..."
          sleep 10
        done
        echo "EC2 instance is ready"

    # Run Ansible playbook to configure the EC2 instance
    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ${{ steps.set_ip.outputs.ec2_ip }}, -u ubuntu --private-key=private_key.pem --extra-vars "ansible_ssh_user=ubuntu" install-packages.yml
